services:
  app:
    container_name: rate-limiter
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - rate-limiter

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - rate-limiter

networks:
  rate-limiter:
    name: rate-limiter
    driver: bridge